### ISSUE TITLE
Make Hyper Mode keybindings more configurable

### ISSUE THREAD

**Issue by bkeepers** [jasonrudolph/keyboard#19]
I have local modifications to the [keybindings for launching apps](https://github.com/jasonrudolph/keyboard/blob/master/hammerspoon/hyper.lua) in Hyper Mode, which makes updating (i.e. when great features like #13 are added) a little more difficult than I'd like.

What would you think about making it easier to allow local overrides for these? Easiest think I could imagine is just a config file like `apps.yml` that is gitignored that gets merged in with the default bindings.

```yml
b: Google Chrome     # "B" for "Browser"
c: Slack             # "C for "Chat"
e: Atom              # "E" for "Editor"
f: Finder            # "F" for "Finder"
g: Mailplane 3       # "G" for "Gmail"
s: Spotify           # "S" for "Spotify"
t: Terminal          # "T" for "Terminal"
```
